#!/usr/bin/env python3
import func
import sys


if __name__ == "__main__":
    black_result = func.call_black()
    changed, unchanged = func.parse_black_result(black_result)
    percentage = func.calculate_percentage(changed, unchanged)

    print(f"Your project is \033[91m{percentage * 100}%\033[0m formatted by black!")

    if len(sys.argv) == 2 and sys.argv[1] == "--generate-badge":
        badge_url = func.generate_badge(percentage)
        print(f"Here is your badge: \033[90m{badge_url}\033[0m")
